# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlackhaulDaemon < Formula
  desc "Outbound-only file daemon for blackhaul — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackhaul"
  version "0.8.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zdods/blackhaul/releases/download/v0.8.4/blackhaul-daemon_0.8.4_darwin_amd64.tar.gz"
      sha256 "82f0d6622643dfdbdaeb68ff668f8eddc0c66862d8e63cfdfc6e378248ef040c"

      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zdods/blackhaul/releases/download/v0.8.4/blackhaul-daemon_0.8.4_darwin_arm64.tar.gz"
      sha256 "1915c9465f6ca15ca4e6e546b28cfcb5ddbf710906408f0839b1b3abbabe6632"

      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zdods/blackhaul/releases/download/v0.8.4/blackhaul-daemon_0.8.4_linux_amd64.tar.gz"
      sha256 "5b9c2250bbee6955ad574f3fd0774404d4c408e303adf1a9be746eef157cb095"
      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zdods/blackhaul/releases/download/v0.8.4/blackhaul-daemon_0.8.4_linux_arm64.tar.gz"
      sha256 "ec38aef6774dd4f957586b1b1d91dc2d43e2750011af2843c590b3256151d549"
      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
  end

  test do
    system "#{bin}/blackhaul-daemon", "--version"
  end
end
