# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackhaul-daemon" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "1fc54696024d3a168beffcfce7ac1b567627c9eb01476301d3cf47c7c29cc8f1"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6fcfbd11ece105dbb95db1fb40a4ec2ac782580a0b5919769b9979bcc41d051"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "57d4727538cecc4a532dbe8f9e429d459f56a08d001a8ca5d9bacc175fe2b0ad"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa5820db45552f9cdf4f72a1dadb7ec7f4e9ded939e533bb8d391ec3362a1c73"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackhaul-daemon"
  desc "Outbound-only file daemon for blackhaul — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackhaul"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackhaul-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackhaul-daemon"]
    end
  end

  # No zap stanza required

end
