# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackhaul-daemon" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "ed1bf165fc6be4f46625e646199ab0fa22d7ec5fa9434f362b38d241e1809f87"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc6b3c3e13d4fabe5298a131ea1f53835c85d1c4a0c1fd8e863e9a104ef984dd"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e6a18c19865c367f05597e7598ba4aa71bdd30f031064364cbce725f99c7d85"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "76f5962279233f5618a21fc019fe77a2bbb8d45402cac947fdd2fb6fa9130f63"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackhaul-daemon"
  desc "Outbound-only file daemon for blackhaul — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackhaul"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackhaul-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackhaul-daemon"]
    end
  end

  # No zap stanza required

end
