# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackbox-daemon" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f16d615c9897e26c67e45814cb964dec9948bf10656f62ecfea9f9adb3aaacc2"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a932a989e3fc4ab38d775ab3c4772fc00d89c40dfe90b072ac97a8c9457ae08"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "361ff3d62bf8bd56e94cf078c3c1f312cb4cc6c1cab9ca0de32d0b787dc90613"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d97c9100fda16e55bfe0f40ef085fad8b5346f57d54cd0d62be0a37982d32be"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackbox-daemon"
  desc "Outbound-only file daemon for blackbox — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackbox-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackbox-daemon"]
    end
  end

  # No zap stanza required

end
