# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackbox-daemon" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e349a00ceafbd1ee0334ce7727ec9271fc3b30dc248a8fb5dd9da621a1e53517"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3daac63a17791175a93c03f7687a909f675a81870073c48f87e45b199f0582c1"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "75f86a67e62b0c545df16a375f6fcd74ab3a83387d8447d116a1e388124c75d7"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "866940fea8fdaadb5bbee9988625df00da9c975e9ba11d2947ba48992b93c7ea"
      url "https://github.com/zdods/blackbox/releases/download/v#{version}/blackbox-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackbox-daemon"
  desc "Outbound-only file daemon for blackbox — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackbox-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackbox-daemon"]
    end
  end

  # No zap stanza required

end
