# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackbox-daemon" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "680a0d17f98db1af56b1af4f23538ffe8691d2c39a5bb5d4762665dab11cdbf5"
      url "https://github.com/zdods/blackbox/releases/download/v0.1.0/blackbox-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "26839bc87e10167483f5c7b7314b242b9d59131f259f16c4f6efcfce4967c9fa"
      url "https://github.com/zdods/blackbox/releases/download/v0.1.0/blackbox-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f83da4d76aef75dc516222cb55b358371e798cfd99c8b8f66e36c7b660e2ec56"
      url "https://github.com/zdods/blackbox/releases/download/v0.1.0/blackbox-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3bf9635b31625e4587588a9e1a4a7218b822262f30516d46a2b310b3b99a6b8"
      url "https://github.com/zdods/blackbox/releases/download/v0.1.0/blackbox-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackbox-daemon"
  desc "Outbound-only file daemon for blackbox — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackbox"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackbox-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackbox-daemon"]
    end
  end

  # No zap stanza required

end
