# This file was generated by GoReleaser. DO NOT EDIT.
cask "blackhaul-daemon" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "7e074e91e5784e0d18b281f74fbbec3a5af4a8a28854b5bcb24bfc0119b12791"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a30264aa1e657db8609492e528cbc822d2226834fb9434d5c6e81a82f0fd751"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8451d302756048a05f8e09376d4650198aa0ae65c3ab070e8b0d529205305755"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "878cebd7291e3ec87bba89d5014ec0e03a6513a98ae3d22be4aa1d86fcaa9860"
      url "https://github.com/zdods/blackhaul/releases/download/v#{version}/blackhaul-daemon_#{version}_linux_arm64.tar.gz"
    end
  end

  name "blackhaul-daemon"
  desc "Outbound-only file daemon for blackhaul — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackhaul"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blackhaul-daemon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blackhaul-daemon"]
    end
  end

  # No zap stanza required

end
