# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BlackhaulDaemon < Formula
  desc "Outbound-only file daemon for blackhaul — browse your machines from a hosted console with zero network config"
  homepage "https://github.com/zdods/blackhaul"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zdods/blackhaul/releases/download/v0.7.1/blackhaul-daemon_0.7.1_darwin_amd64.tar.gz"
      sha256 "33025499426510b9f9d619bd15125a5afcad8755546de72ecb71b52952e0c7a6"

      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zdods/blackhaul/releases/download/v0.7.1/blackhaul-daemon_0.7.1_darwin_arm64.tar.gz"
      sha256 "6d950c7155d6a79538c3ec940e6a1a1e654ef4c428f48304d0a4d466aad3d65f"

      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zdods/blackhaul/releases/download/v0.7.1/blackhaul-daemon_0.7.1_linux_amd64.tar.gz"
      sha256 "4cbbdd90dece328c22b7eac6e36dfc8d66d552cfd7ef5de7da884e08fe175222"
      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zdods/blackhaul/releases/download/v0.7.1/blackhaul-daemon_0.7.1_linux_arm64.tar.gz"
      sha256 "4b55e32b32d2df3f941a27c4d4d9e85e184875ad6d43bc7f775722b6fecfd45e"
      define_method(:install) do
        bin.install "blackhaul-daemon"
      end
    end
  end

  test do
    system "#{bin}/blackhaul-daemon", "--version"
  end
end
